# Generated by Django 4.2.2 on 2023-06-13 07:20

from django.db import migrations, models
import loan.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealStateLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('real_state_total_value', models.FloatField()),
                ('entry_value', models.FloatField()),
                ('loan_total_value', models.FloatField()),
                ('monthly_income', models.FloatField()),
                ('number_of_installments', models.IntegerField()),
                ('user_id', models.CharField(max_length=255)),
                ('interest_rate_per_year', models.FloatField()),
                ('value_per_month', models.FloatField()),
                ('installments_payed', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active', loan.manager.ActiveBaseEntityManager()),
                ('objects', loan.manager.DefaultEntityManager()),
            ],
        ),
        migrations.CreateModel(
            name='RealStateLoanSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('real_state_total_value', models.FloatField()),
                ('entry_value', models.FloatField()),
                ('loan_total_value', models.FloatField()),
                ('monthly_income', models.FloatField()),
                ('number_of_installments', models.IntegerField()),
                ('user_id', models.CharField(max_length=255)),
                ('interest_rate_per_year', models.FloatField()),
                ('value_per_month', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active', loan.manager.ActiveBaseEntityManager()),
                ('objects', loan.manager.DefaultEntityManager()),
            ],
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='fee_percent_per_year',
            new_name='fee_percent',
        ),
    ]
