# Generated by Django 4.2.2 on 2023-06-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_realstateloan_realstateloansimulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstateloan',
            name='installments_payed',
            field=models.IntegerField(default=0),
        ),
    ]
